#import <PEGKit/PKParser.h>

enum {
    STLOGEXPRESSIONPARSER_TOKEN_KIND_NE = 14,
    STLOGEXPRESSIONPARSER_TOKEN_KIND_FALSE = 15,
    STLOGEXPRESSIONPARSER_TOKEN_KIND_GE = 16,
    STLOGEXPRESSIONPARSER_TOKEN_KIND_LOGROOT = 17,
    STLOGEXPRESSIONPARSER_TOKEN_KIND_IS = 18,
    STLOGEXPRESSIONPARSER_TOKEN_KIND_EQ = 19,
    STLOGEXPRESSIONPARSER_TOKEN_KIND_LT_SYM = 20,
    STLOGEXPRESSIONPARSER_TOKEN_KIND_OPEN_BRACKET = 21,
    STLOGEXPRESSIONPARSER_TOKEN_KIND_TRUE = 22,
    STLOGEXPRESSIONPARSER_TOKEN_KIND_NIL = 23,
    STLOGEXPRESSIONPARSER_TOKEN_KIND_LOGALL = 24,
    STLOGEXPRESSIONPARSER_TOKEN_KIND_DOT = 25,
    STLOGEXPRESSIONPARSER_TOKEN_KIND_GT_SYM = 26,
    STLOGEXPRESSIONPARSER_TOKEN_KIND_CLOSE_BRACKET = 27,
    STLOGEXPRESSIONPARSER_TOKEN_KIND_LE = 28,
    STLOGEXPRESSIONPARSER_TOKEN_KIND_YES_UPPER = 29,
    STLOGEXPRESSIONPARSER_TOKEN_KIND_UNDERSCORE = 30,
    STLOGEXPRESSIONPARSER_TOKEN_KIND_NO_UPPER = 31,
};

@interface STLogExpressionParser : PKParser

@end

